# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.S. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data

# Build settings
markdown: kramdown

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  indicators:
    output: true
  goals:
    output: true    

# Prose configuration
prose: 
  rooturl: "data"
  ignore: ['/css', '/_includes', '/_layouts', '/scripts', '/', 'planning_district_boundaries.json', '*.yml', '*.geojson']
