# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.S. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data

#Github Repo
repo_name: sdg-indicators
branch: gh-pages
org_name: GSA

# Build settings
markdown: kramdown

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  indicators:
    output: true
  goals:
    output: true    

# Prose configuration
prose: 
  ignore: ['/assets', '/_includes', '/_layouts', '/scripts', '/sass' ]
  metadata:
    _indicators:
      - name: "sdg_goal"
        field: 
            element: text
            label: "SDG Goal #"  
      - name: "indicator"
        field: 
            element: text
            label: "Indicator #"  
      - name: "indicator_variable"
        field: 
            element: text
            label: "Indicator Variable"  
      - name: "graph"
        field: 
            element: text
            label: "Graph Type"  
      - name: "variable_description"
        field: 
            element: text
            label: "Variable Description"  
      - name: "variable_notes"
        field: 
            element: text
            label: "Variable Notes"  
      - name: "source_title"
        field: 
            element: text
            label: "Source Title"  
      - name: "source_url"
        field: 
            element: text
            label: "Source URL"  
      - name: "source_notes"
        field: 
            element: text
            label: "Source Notes"  
      - name: "indicator_name"
        field: 
            element: text
            label: "Indicator Name"  
      - name: "goal_and_target_addressed"
        field: 
            element: text
            label: "Goal and Target Addressed"  
      - name: "indicator_definition"
        field: 
            element: text
            label: "Indicator Definition"  
      - name: "actual_indicator_available"
        field: 
            element: text
            label: "Actual Indicator Available"  
      - name: "method_of_computation"
        field: 
            element: text
            label: "Method of Computation"  
      - name: "sources_and_data_collection"
        field: 
            element: text
            label: "Sources and Data Collection"  
      - name: "international_and_national_references"
        field: 
            element: text
            label: "International and National References"  
      - name: "unit_of_measure"
        field: 
            element: text
            label: "Unit of Measure"  
      - name: "disaggregation_1"
        field: 
            element: text
            label: "Disaggregation 1"  
      - name: "disaggregation_2"
        field: 
            element: text
            label: "Disaggregation 2"  
      - name: "time_reference"
        field: 
            element: text
            label: "Time Reference"  
      - name: "periodicity"
        field: 
            element: text
            label: "Periodicity"  
      - name: "date_of_release_by_nso"
        field: 
            element: text
            label: "Date of Release by NSO"  
      - name: "scheduled_update"
        field: 
            element: text
            label: "Scheduled Update"  
      - name: "comments_and_limitations"
        field: 
            element: text
            label: "Comments and Limitations"  