# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.S. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data

#Github Repo
repo_name: sdg-indicators
branch: gh-pages
org_name: GSA

# Build settings
markdown: kramdown

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  indicators:
    output: true
  goals:
    output: true    

# Prose configuration
prose: 
  ignore: ['/assets', '/_includes', '/_layouts', '/scripts', '/sass' ]
  metadata:
    _indicators:
      - name: "sdg_goal"
        field: 
            element: text
        label: "SDG Goal #"  
      - name: "indicator"
        field: 
            element: text
        label: "Indicator #"  
      - name: "indicator_variable"
        field: 
            element: text
        label: "Indicator Variable"  
      - name: "graph"
        field: 
            element: text
        label: "graph"  
      - name: "variable_description"
        field: 
            element: text
        label: "variable_description"  
      - name: "variable_notes"
        field: 
            element: text
        label: "variable_notes"  
      - name: "source_title"
        field: 
            element: text
        label: "source_title"  
      - name: "source_url"
        field: 
            element: text
        label: "source_url"  
      - name: "source_notes"
        field: 
            element: text
        label: "source_notes"  
      - name: "indicator_name"
        field: 
            element: text
        label: "indicator_name"  
      - name: "goal_and_target_addressed"
        field: 
            element: text
        label: "goal_and_target_addressed"  
      - name: "indicator_definition"
        field: 
            element: text
        label: "indicator_definition"  
      - name: "actual_indicator_available"
        field: 
            element: text
        label: "actual_indicator_available"  
      - name: "method_of_computation"
        field: 
            element: text
        label: "method_of_computation"  
      - name: "sources_and_data_collection"
        field: 
            element: text
        label: "sources_and_data_collection"  
      - name: "international_and_national_references"
        field: 
            element: text
        label: "international_and_national_references"  
      - name: "unit_of_measure"
        field: 
            element: text
        label: "unit_of_measure"  
      - name: "disaggregation_1"
        field: 
            element: text
        label: "disaggregation_1"  
      - name: "disaggregation_2"
        field: 
            element: text
        label: "disaggregation_2"  
      - name: "time_reference"
        field: 
            element: text
        label: "field name"  
      - name: "periodicity"
        field: 
            element: text
        label: "field name"  
      - name: "date_of_release_by_nso"
        field: 
            element: text
        label: "field name"  
      - name: "scheduled_update"
        field: 
            element: text
        label: "field name"  
      - name: "comments_and_limitations"
        field: 
            element: text
        label: "field name"  